"""empty message

Revision ID: 531a92fd47c0
Revises: 
Create Date: 2022-12-02 10:19:08.168929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531a92fd47c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend__request',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_sent_by', sa.Integer(), nullable=True),
    sa.Column('request_sent_to', sa.Integer(), nullable=True),
    sa.Column('request_status', sa.Enum('P', 'A', 'R'), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['request_sent_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['request_sent_to'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=150), nullable=False),
    sa.Column('group_description', sa.Text(), nullable=False),
    sa.Column('group_founder', sa.Integer(), nullable=True),
    sa.Column('group_creation_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['group_founder'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('group__members',
    sa.Column('group_member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_group_id', sa.Integer(), nullable=True),
    sa.Column('member', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['chat_group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['member'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('group_member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group__members')
    op.drop_table('groups')
    op.drop_table('friend__request')
    # ### end Alembic commands ###
