"""empty message

Revision ID: 9c37fb0108e5
Revises: 
Create Date: 2022-11-09 14:06:11.585265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c37fb0108e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_stack', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'techstack', ['user_stack'], ['stack_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_stack')
    # ### end Alembic commands ###
