"""empty message

Revision ID: cbe705506641
Revises: d52af53a068f
Create Date: 2022-11-18 14:27:08.465305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe705506641'
down_revision = 'd52af53a068f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugsheet', sa.Column('bug_image', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugsheet', 'bug_image')
    # ### end Alembic commands ###
