"""empty message

Revision ID: d52af53a068f
Revises: 9c37fb0108e5
Create Date: 2022-11-10 11:24:16.193444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52af53a068f'
down_revision = '9c37fb0108e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox',
    sa.Column('msg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('msg_sender', sa.Integer(), nullable=True),
    sa.Column('msg_recipient', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('datesent', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['msg_recipient'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['msg_sender'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('msg_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inbox')
    # ### end Alembic commands ###
